name = "NeuralNetwork"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NeuralNetwork"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "PhysLean"
git = "https://github.com/HepLean/PhysLean"
rev = "main"

[[lean_lib]]
name = "NeuralNetwork"

[[lean_lib]]
name = "Mathematics"
